sudo: true

    # fully specify builds, include can't dynamically expand matrix entries
    # relative order of sudo and env is important so that addons: is recognized
    - os: linux
      dist: trusty
      sudo: required
      env: TARGET="linux"
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-4.9
          - g++-4.9
matrix:
  include:
    - os: osx
    - os: linux
      dist: trusty
    - os: linux
      sudo: false
      cache:
        directories:
        - ~/.pyenv

env:
- PYENV_PYTHON_VERSION=3.5.0

before_install:
- ci/travis/before_install.sh
install:
- ci/travis/build.sh
script:
- ci/travis/test.sh
after_success:
- ci/travis/after_success.sh
before_deploy:
- ci/travis/before_deploy.sh

deploy:
  provider: releases
  api_key:
    secure: MUdvTDBeCxO9d/EpzIhr+QYra/KxgYkXX6177SjqWCWDqw9xB3fwSUj8I9ht9DGtwVdadtveumtvLw3pbtVIR0GtIPC9pyvtNz4j6T4Ei3TSE6+StXdMK4NnInvPeTRlobGL+9sZt9MwheJwZ8YGewhBcR0F5UzVfxWeSSrxmyk=
  file: sakia-${TRAVIS_OS_NAME}.zip
  skip_cleanup: true
  on:
    tags: true
