os: osx
before_install:
  # Install and configure pyenv
  - ci/travis/before_install.sh

install:
  - pip install coveralls cx_Freeze
  - pip install -r requirements.txt
  - python gen_resources.py
  - python gen_translations.py
  - python setup.py build

script:
  - coverage run --source=sakia.core,sakia.gui,sakia.models run_tests.py

after_success:
  - coverage -rm
  - coveralls
