os:
 - osx
sudo: false
language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.4"
before_install:
  # Update
  - pwd
  # Install and configure pyenv
  - ci/travis/before_install.sh

install:
  - pip install coveralls cx_Freeze
  - pip install -r requirements.txt
  - python gen_resources.py
  - python gen_translations.py
  - python setup.py build

script:
  - coverage run --source=sakia.core,sakia.gui,sakia.models run_tests.py

after_success:
  - coverage -rm
  - coveralls
